### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by hannesa2**
Now I'm able to build, it's related to #1

### CODE REVIEW

**Comment by hannesa2** [comment]
But now, I  run into this after clicking an image
image

**Comment by DanteAndroid** [comment]
Thanks for your PR. I already updated them and fix some stale bug, please check it out.

**Comment by hannesa2** [comment]
> Thanks for your PR. I already updated them and fix some stale bug, please check it out.

Sorry, nothing is solved on recent master. 
When you close the solution, I can't help anymore

**Comment by DanteAndroid** [comment]
What do you mean? I've run it, no errors now.

**Comment by DanteAndroid** [comment]
I'm sorry. That error occurs after I updated `compileSdkVersion` to 30. Already fixed.

**Pull request closed without merging**
